var columnWidth=240,columnSpacing=10,numPerColumnSmall=4,numPerColumnBig=5,debugging=0,initialLoadCompleted=0,userID=0,userName="",userToken="",markersArray=[],singleDealMarkersArray=[],singleDeal={},singleCategory=0,listScrollPosition,listMarker,query="",utm="direct",currentSortBy="SOLD",currSWLat=-1,currSWLng=-1,currNELat=-1,currNELng=-1,currBoundingBoxSizeMultiplier=1,view="LIST",pages=1,mapViewDealID="",cityEdition=-1,changedEditionWhileInListView=0,userEdition=-1,userZipCode=-1,maxDealDistance=
0,cityString,zip,zipLat,zipLng,historyObject=[],cityLat=[0,0,0,47.614495,45.5235,37.775,37.342867,32.7153,37.448424,34.0522,47.268048,40.759306,41.888988,42.358433,33.781145,28.538537,29.760205,38.894774,25.78969,32.802282,39.740986,36.114858,30.267518,39.958175,41.51012,44.963826,33.452068,33.73005,39.287811,39.10662,42.33355,38.628404,40.440415,29.424124,29.951067],cityLng=[0,0,0,-122.25386,-122.676,-122.418,-121.894684,-117.156,-122.159042,-118.243,-122.444,-73.984884,-87.6244,-71.059957,-84.357147,
-81.379681,-95.36931,-77.036476,-80.225601,-96.768951,-104.98741,-115.173111,-97.74313,-75.125885,-81.672363,-93.178482,-112.05986,-117.865448,-76.605263,-94.561386,-83.029861,-90.182648,-79.997635,-98.493719,-90.071583],cityZoom=[12,12,12,12,12,13,12,12,11,10,12,14,12,12,12,12,12,12,12,10,12,12,12,12,12,10,10,10,12,12,12,12,12,11,11],swLat,swLng,neLat,neLng,map,selectedMarkerIndex=-1,selectedMarkerImageIndex=0,companies=[],cities=[],citiesReverse=[],cities_url=[],showYelp=0,showCompany=0;
companies[0]="No company at this index";companies[1]="Groupon";companies[2]="Living Social";companies[3]="BuyWithMe";companies[4]="Tippr";companies[5]="TravelZoo";companies[6]="Angies List";companies[7]="Gilt City";companies[8]="Yollar";companies[9]="Zozi";companies[10]="Bloomspot";companies[11]="ScoutMob";companies[12]="Amazon Local";companies[13]="kgbdeals";companies[14]="Lifebooker";companies[15]="DealOn";companies[16]="Eversave";companies[17]="LS Escapes";companies[18]="Google Offers";
companies[19]="Get My Perks";companies[20]="Voice Deals";companies[21]="Munch On Me";companies[22]="Doodle Deals";companies[23]="Juice in the City";companies[24]="Schwaggle";companies[25]="Home Run";companies[26]="Bargain Bee";companies[27]="Signpost";companies[28]="Crowd Seats";companies[29]="Landmarks Great Deals";companies[30]="DealFind";companies[31]="Restaurant.com";companies[32]="Pinchit";companies[33]="Goldstar";companies[34]="OnSale";companies[35]="Living Social";companies[36]="Entertainment.com";
companies[37]="Thrillist";companies[38]="Savored";companies[39]="MSN Offers";companies[40]="CBS Local Offers";companies[41]="Crowd Savings";cities[1]="";cities[2]="Nation";cities[3]="Seattle";cities[4]="Portland";cities[5]="San Francisco";cities[6]="San Jose";cities[7]="San Diego";cities[8]="Silicon Valley";cities[9]="Los Angeles";cities[10]="Tacoma";cities[11]="New York";cities[12]="Chicago";cities[13]="Boston";cities[14]="Atlanta";cities[15]="Orlando";cities[16]="Houston";cities[17]="Washington, D.C.";
cities[18]="Miami";cities[19]="Dallas";cities[20]="Denver";cities[21]="Las Vegas";cities[22]="Austin";cities[23]="Philadelphia";cities[24]="Cleveland";cities[25]="Minneapolis/St.Paul";cities[26]="Phoenix";cities[27]="Orange County";cities[28]="Baltimore";cities[29]="Kansas City";cities[30]="Detroit";cities[31]="St. Louis";cities[32]="Pittsburgh";cities[33]="San Antonio";cities[34]="New Orleans";cities[35]="Honolulu";cities[36]="Sacramento";cities[37]="Salt Lake City";cities[38]="Tampa";
cities[39]="Cincinnati";cities[40]="Indianapolis";cities[41]="Madison";cities[42]="Milwaukee";cities[43]="Albany";cities[44]="Palm Beach";cities[45]="Birmingham";cities[46]="Columbus";cities[47]="Oklahoma City";cities[48]="Raleigh";cities[49]="Charlotte";cities[50]="Charleston";citiesReverse.nation=2;citiesReverse.seattle=3;citiesReverse.portland=4;citiesReverse["san-francisco"]=5;citiesReverse["san-jose"]=6;citiesReverse["san-diego"]=7;citiesReverse["silicon-valley"]=8;
citiesReverse["los-angeles"]=9;citiesReverse.tacoma=10;citiesReverse["new-york"]=11;citiesReverse.chicago=12;citiesReverse.boston=13;citiesReverse.atlanta=14;citiesReverse.orlando=15;citiesReverse.houston=16;citiesReverse.washington=17;citiesReverse.miami=18;citiesReverse.dallas=19;citiesReverse.denver=20;citiesReverse["las-vegas"]=21;citiesReverse.austin=22;citiesReverse.philadelphia=23;citiesReverse.cleveland=24;citiesReverse.minneapolis=25;citiesReverse.phoenix=26;
citiesReverse["orange-county"]=27;citiesReverse.baltimore=28;citiesReverse["kansas-city"]=29;citiesReverse.detroit=30;citiesReverse["st-louis"]=31;citiesReverse.pittsburgh=32;citiesReverse["san-antonio"]=33;citiesReverse["new-orleans"]=34;citiesReverse.honolulu=35;citiesReverse.sacramento=36;citiesReverse["salt-lake-city"]=37;citiesReverse.tampa=38;citiesReverse.cincinnati=39;citiesReverse.indianapolis=40;citiesReverse.madison=41;citiesReverse.milwaukee=42;citiesReverse.albany=43;
citiesReverse["palm-beach"]=44;citiesReverse.birmingham=45;citiesReverse.columbus=46;citiesReverse["oklahoma-city"]=47;citiesReverse.raleigh=48;citiesReverse.charlotte=49;citiesReverse.charleston=50;cities_url[1]="other";cities_url[2]="nation";cities_url[3]="seattle";cities_url[4]="portland";cities_url[5]="san-francisco";cities_url[6]="san-jose";cities_url[7]="san-diego";cities_url[8]="silicon-valley";cities_url[9]="los-angeles";cities_url[10]="tacoma";cities_url[11]="new-york";cities_url[12]="chicago";
cities_url[13]="boston";cities_url[14]="atlanta";cities_url[15]="orlando";cities_url[16]="houston";cities_url[17]="washington";cities_url[18]="miami";cities_url[19]="dallas";cities_url[20]="denver";cities_url[21]="las-vegas";cities_url[22]="austin";cities_url[23]="philadelphia";cities_url[24]="cleveland";cities_url[25]="minneapolis";cities_url[26]="phoenix";cities_url[27]="orange-county";cities_url[28]="baltimore";cities_url[29]="kansas-city";cities_url[30]="detroit";cities_url[31]="st-louis";
cities_url[32]="pittsburgh";cities_url[33]="san-antonio";cities_url[34]="new-orleans";cities_url[35]="honolulu";cities_url[36]="sacramento";cities_url[37]="salt-lake-city";cities_url[38]="tampa";cities_url[39]="cincinatti";cities_url[40]="indianapolis";cities_url[41]="madison";cities_url[42]="milwaukee";cities_url[43]="albany";cities_url[44]="palm-beach";cities_url[45]="birmingham";cities_url[46]="columbus";cities_url[47]="oklahoma-city";cities_url[48]="raleigh";cities_url[49]="charlotte";
cities_url[50]="charleston";categoryIDToSetID=[,1,1,1,1,1];categoryIDToSetID[52]=1;categoryIDToSetID[54]=1;categoryIDToSetID[55]=1;categoryIDToSetID[6]=2;categoryIDToSetID[7]=2;categoryIDToSetID[8]=3;categoryIDToSetID[9]=4;categoryIDToSetID[10]=5;categoryIDToSetID[11]=5;categoryIDToSetID[12]=5;categoryIDToSetID[13]=5;categoryIDToSetID[14]=5;categoryIDToSetID[15]=6;categoryIDToSetID[16]=6;categoryIDToSetID[17]=6;categoryIDToSetID[18]=6;categoryIDToSetID[46]=6;categoryIDToSetID[19]=7;
categoryIDToSetID[20]=7;categoryIDToSetID[21]=7;categoryIDToSetID[22]=7;categoryIDToSetID[23]=7;categoryIDToSetID[24]=7;categoryIDToSetID[25]=7;categoryIDToSetID[26]=7;categoryIDToSetID[27]=7;categoryIDToSetID[28]=7;categoryIDToSetID[29]=7;categoryIDToSetID[47]=7;categoryIDToSetID[48]=7;categoryIDToSetID[50]=7;categoryIDToSetID[53]=7;categoryIDToSetID[56]=7;categoryIDToSetID[57]=7;categoryIDToSetID[58]=7;categoryIDToSetID[59]=7;categoryIDToSetID[30]=8;categoryIDToSetID[31]=8;
categoryIDToSetID[32]=8;categoryIDToSetID[33]=8;categoryIDToSetID[34]=8;categoryIDToSetID[51]=8;categoryIDToSetID[35]=9;categoryIDToSetID[36]=9;categoryIDToSetID[37]=9;categoryIDToSetID[38]=9;categoryIDToSetID[39]=9;categoryIDToSetID[40]=9;categoryIDToSetID[41]=9;categoryIDToSetID[49]=9;categoryIDToSetID[42]=10;categoryIDToSetID[43]=10;categoryIDToSetID[44]=11;categoryIDToSetID[45]=12;
var vacationsMax=0,yelpTimeout=0,yelpTimeoutList=0,galleryMapTimeout=0,galleryMapBlocker=0,messageTimeout=0,hoverImageTimer=0,hoverImageIndex=0,marker0=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(0,0),new google.maps.Point(7,7)),marker1=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(13,0),new google.maps.Point(7,7)),marker2=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,
13),new google.maps.Point(26,0),new google.maps.Point(7,7)),marker3=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(39,0),new google.maps.Point(7,7)),marker4=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(52,0),new google.maps.Point(7,7)),marker5=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(65,0),new google.maps.Point(7,7)),marker6=new google.maps.MarkerImage("/images/markers.png",
new google.maps.Size(13,13),new google.maps.Point(78,0),new google.maps.Point(7,7)),marker7=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(91,0),new google.maps.Point(7,7)),marker8=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(104,0),new google.maps.Point(7,7)),marker9=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(117,0),new google.maps.Point(7,
7)),marker10=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(130,0),new google.maps.Point(7,7)),marker11=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(143,0),new google.maps.Point(7,7)),marker12=new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(156,0),new google.maps.Point(7,7));categoriesRank1_DB_array=[];categoriesRank1DBDirtyBit=1;
categoriesRank2_DB_array=[];var infiniteScrollTimeout=categoriesRank2DBDirtyBit=1,login_div=$("#login-div").detach(),change_password_div=$("#change-password-div").detach(),forgot_password_div=$("#forgot-password-div").detach(),city_selector=$("#city-selector").detach(),brownMapStyle;
function load(){debug("***********************************");debug("********** START OF LOAD() ********");debug("***********************************");debug("At the start of load(), urlParams is: "+urlParams);debug("At the start of load(), the last_view cookie is:: "+$.cookie("last_view"));$(window).bind("popstate",function(a){debug("||||||||||| POP |||||||||||");if(a=a.originalEvent.state){debug(a.stateParams);historyObject.pop();var b=view;parseStateString(a.stateParams);changeView(view);"SINGLE-DEAL"==
b&&100<$("#container").html().length?loadAndDisplay(1):loadAndDisplay()}setTimeout("window.scrollTo(0, listScrollPosition);",15)});userID=isLoggedIn();isLoggedIn()&&initLoggedIn();$("#top-bar-welcome").hide();$("#top-bar").show();var a={styles:brownMapStyle,zoom:cityZoom[cityEdition],center:new google.maps.LatLng(cityLat[cityEdition],cityLng[cityEdition]),mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:!1,zoomControl:!0,zoomControlOptions:{style:google.maps.ZoomControlStyle.LARGE,position:google.maps.ControlPosition.TOP_RIGHT}};
map=new google.maps.Map(document.getElementById("map"),a);a={styles:brownMapStyle,zoom:12,mapTypeId:google.maps.MapTypeId.ROADMAP,streetViewControl:!1,mapTypeControl:!1,zoomControlOptions:{position:google.maps.ControlPosition.RIGHT_CENTER}};listMap=new google.maps.Map(document.getElementById("gallery-map"),a);listMarker=new google.maps.Marker({map:listMap});google.maps.event.addListener(map,"idle",function(){"LIST"==view||"SINGLE-DEAL"==view||(cityEdition=calculateCityEditionFromLatLng(map.getCenter().lat(),
map.getCenter().lng()),$("#city-name").html(cities[cityEdition].toLowerCase()),loadAndDisplay(),"Explorer"==BrowserDetect.browser&&$("div").css("background-color",""))});resizeMap();null==$.cookie("welcome_cookie")?$.cookie("welcome_cookie","1",{expires:1E3,path:"/"}):(a=parseInt($.cookie("welcome_cookie")),$.cookie("welcome_cookie",a+1,{expires:1E3,path:"/"}));debug("The welcome count is "+$.cookie("welcome_cookie"));debug("UserID: "+isLoggedIn());if("?"!=urlParams&&""!=urlParams&&-1==urlParams.indexOf("action"))parseStateString(urlParams),
debug("calling changeview with arg "+view+" and edition "+cityEdition+" in load() - urlparams present: "+urlParams),"SINGLE-DEAL"!=view&&logout(),changeView(view),loadAndDisplay();else if(isLoggedIn())if(-1!=urlParams.indexOf("action")&&-1!=urlParams.indexOf("show_settings"))changeView("EMAIL"),loadAndDisplayEmail();else{-1!=urlParams.indexOf("action")&&-1!=urlParams.indexOf("email_login")&&mpq.track("User loaded site from email 'see all deals' link",{mp_note:"User loaded site from email 'see all deals' link",
City:cities[cityEdition],UserID:userID});var b;jQuery.ajax({type:"GET",url:"/get_user_data.php?user_id="+userID+"&token="+userToken,success:function(a){b=$.parseJSON(a)},async:!1});cityEdition=parseInt(b.edition);userEdition=parseInt(b.edition);userZipCode=parseInt(b.zipcode);maxDealDistance=parseInt(b.max_deal_distance);debug("calling changeview with arg "+view+" and edition "+cityEdition+" in load() - from DB");utm+="_"+welcomeScreen;changeView(view);changeEdition(cityEdition)}else null!=$.cookie("last_view")?
isTooOld($.cookie("timestamp"))?($.cookie("timestamp",(new Date).getTime(),{expires:1E3,path:"/"}),debug("calling changeview with arg "+view+" and edition "+cityEdition+" in load() because last_view' cookie was present but was expired, so showing default view and reseting cookie 'timestamp'"),changeView(view),changeEdition(cityEdition)):(parseStateString($.cookie("last_view")),debug("calling changeview with arg "+view+" and edition "+cityEdition+" in load() - going off cookie: "+$.cookie("last_view")),
changeView(view),loadAndDisplay()):(debug("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ERROR XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: There should ALWAYS be a last_view cookie"),debug("calling changeview with arg "+view+" and edition "+cityEdition+" in load() - fresh load, neither params nor cookie to guide"),utm+="_"+welcomeScreen,changeView(view),changeEdition(cityEdition));pushState();debug("initialLoadCompleted!");initialLoadCompleted=1;debug("===================================");debug("=========== END OF LOAD() =========");
debug("===================================");debug("")}
function loadRegistrations(){debug("> loadRegistrations()");$("input[placeholder], textarea[placeholder]").placeholder();$(window).resize(resizeMap);$("#unhide-categories").poshytip({className:"tip-black",showOn:"none",alignTo:"target",alignX:"center",offsetX:0,offsetY:15});$("#dealupa-title").poshytip({className:"tip-city-selector",content:city_selector.html(),showOn:"none",alignTo:"target",alignX:"center",offsetX:0,offsetY:2});$("#city-selector").remove();$("#gallery-map-panel").mouseenter(function(){debug("on map");
clearTimeout(galleryMapTimeout);galleryMapBlocker=1});$("#gallery-map-panel").mouseleave(function(){debug("off map");galleryMapBlocker=0});$("#yelp-link").mouseover(function(){$("#yelp-reviews").show();clearTimeout(yelpTimeout)});$("#yelp-link").mouseout(function(){yelpTimeout=setTimeout("clearYelp()",200)});$("#yelp-reviews").mouseover(function(){clearTimeout(yelpTimeout)});$("#yelp-reviews").mouseout(function(){yelpTimeout=setTimeout("clearYelp()",200)});$("#list-yelp-reviews").mouseover(function(){clearTimeout(yelpTimeoutList)});
$("#list-yelp-reviews").mouseout(function(){yelpTimeoutList=setTimeout("clearYelpList()",200)});$("#top-bar-search-box").keypress(function(a){var b=a.which,c=String.fromCharCode(b).toLowerCase();if(null==b||0==b||8==b||9==b||13==b||27==b)return!0;if(-1==" abcdefghijklmnopqrstuvwxyz0123456789".indexOf(c))return a.preventDefault(),!1});$("#sort-zip").keypress(function(a){var b=a.which,c=String.fromCharCode(b).toLowerCase();if(null==b||0==b||8==b||9==b||13==b||27==b)return!0;if(-1==" 0123456789".indexOf(c))return a.preventDefault(),
!1});$(window).scroll(function(){"LIST"==view&&initialLoadCompleted&&($(window).scrollTop()>=$(document).height()-$(window).height()-3E3&&infiniteScrollTimeout)&&(mpq.track("Infinite scroll",{mp_note:"Infinite scroll triggered",City:cities[cityEdition],UserID:userID}),infiniteScrollTimeout=0,debug("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! LOADING MORE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"),pages++,loadAndDisplayDeals(!0))});$("#top-bar-search-box").keyup(function(a){if(13==
(a.keyCode||a.which))executeSearch(),a.preventDefault()});$("#sort-zip").keyup(function(a){if(13==(a.keyCode||a.which))resortListView("DISTANCE"),a.preventDefault()});$("#move-map-input").keyup(function(a){13==a.keyCode&&$("#move-map-button").click()});$("#login-password").keyup(function(a){var b=a.keyCode||a.which;13==b&&(emailLogin(),a.preventDefault());27==b&&(removeLogin(),a.preventDefault())});$("#reset-password").keyup(function(a){if(13==(a.keyCode||a.which))changePassword(),a.preventDefault()});
$("#forgot-email").keyup(function(a){var b=a.keyCode||a.which;13==b&&(sendNewPassword(),a.preventDefault());27==b&&(removeLogin(),a.preventDefault())});$("#signup-email, #signup-password").keyup(function(a){if(13==(a.keyCode||a.which))signupUser(),a.preventDefault()});$("#signup-zipcode").keyup(function(a){var b=a.keyCode||a.which;13==b&&(recordZipcode(),a.preventDefault());27==b&&(initialLoadCompleted||load(),removeWelcome(),a.preventDefault())});$("a").click(function(a){if(a.metaKey||a.ctrlKey)return debug("YOU ARE HOLDING DOWN CTRL!"),
!1});$("#dealupa-title").click(function(a){showEditionSelector(a,this)});$("#unhide-categories").click(function(a){toggleHiddenCategories(a,this)});brownMapStyle=[{stylers:[{saturation:-90},{lightness:16},{gamma:0.8}]},{featureType:"poi.park",stylers:[{hue:"#a1ff00"},{saturation:45},{gamma:0.93},{lightness:-11}]},{featureType:"landscape",stylers:[{saturation:27},{gamma:0.49},{hue:"#ffc300"},{lightness:10}]},{featureType:"water",stylers:[{hue:"#00b2ff"},{lightness:-8},{saturation:20}]},{featureType:"road.arterial",
elementType:"geometry",stylers:[{hue:"#ff9900"},{saturation:10},{lightness:-3},{gamma:0.94}]},{featureType:"road.highway",elementType:"geometry",stylers:[{hue:"#ff6e00"},{lightness:-24},{gamma:1.62},{saturation:24}]},{featureType:"road.arterial",elementType:"labels",stylers:[{lightness:45},{gamma:0.52},{saturation:5},{hue:"#ff9900"},{visibility:"on"}]},{featureType:"water",stylers:[{visibility:"on"}]}]}
function isTooOld(a){debug("cookie ts: "+a);debug("min ts allowed: 1331884904000");if(null==a||""==a||1331884904E3>a)return debug("COOKIE IS TOO OLD"),!0;debug("COOKIE IS GOOD (i.e., not too old)");return!1}
function showEditionSelector(a,b){debug("> showEditionSelector(event, elem)");$("#dealupa-title").poshytip("show");a.stopPropagation();$("html").one("click",function(){$("#"+b.getAttribute("id")).poshytip("hide")});$("#"+b.getAttribute("id")+"-tip").unbind("click");$("#"+b.getAttribute("id")+"-tip").click(function(a){a.stopPropagation()})}
function deleteCategory(a){debug("> deleteCategory(category)");updateCategories("DELETE",[a]);setNumberHidden();var b="";isLoggedIn()||(b="<a href='/'>Sign up</a> to get a daily email of just the kind of deals you're interested in.");showMessage("You've hidden all &#160;<b>"+categories[a]+"</b>&#160; deals.",b,5E3)}
function setCategoryTo1(a){debug("> setCategoryTo1(category)");updateCategories("SET_TO_1",[a]);setNumberHidden();$("#unhide-categories").poshytip("hide");showMessage("You've turned on &#160;<b>"+categories[a]+"</b>&#160; deals.","",5E3)}
function setNumberHidden(){debug("> setNumberHidden()");var a=categories.length-getVisibleCategories().length-1;0==a?($("#num-hidden-categories").fadeOut(),$("#unhide-categories").fadeOut()):(1==a?$("#num-hidden-categories").html("Hiding <span style='font-weight:700'>"+a+"</span> category&#160;&#160;"):$("#num-hidden-categories").html("Hiding <span style='font-weight:700'>"+a+"</span> categories&#160;&#160;"),$("#num-hidden-categories").fadeIn(),$("#unhide-categories").fadeIn())}
function setYelp(a){$("#filter-yelp-0").removeClass("down");for(var b=3;5>=b;b++)$("#filter-yelp-"+b).removeClass("down");$("#filter-yelp-"+a).addClass("down");showYelp=a}
function toggleHiddenCategories(a,b){debug("> toggleHiddenCategories(event, elem)");for(var c=getVisibleCategories(),e=categories.length-c.length-1,f=Math.ceil(e/10),e=Math.ceil(e/f),g=[],h=0,j=1;j<categories.length;j++)-1==c.indexOf(j)&&(g[h]=0==h%e?"<div>":"<div style='margin-top:20px;'>",g[h]+="<span class='category category-set-"+categoryIDToSetID[j]+"'>"+categories[j]+"</span> - <a href='javascript:void(0);' onclick='setCategoryTo1("+j+"); loadAndDisplay(); pushState();'>Show</a></div>",h++);
h="<div><table><tbody><tr>";for(j=0;j<f;j++)h+="<td style='vertical-align:top'>"+g.slice(j*e,Math.min(j*e+e,c.length)).join("")+"</td>",j+1!=f&&(h+="<td>&nbsp;&nbsp;</td>");$("#unhide-categories").poshytip("update",h+"</tr></tbody></table></div>");$("#unhide-categories").poshytip("show");a.stopPropagation();$("html").one("click",function(){$("#"+b.getAttribute("id")).poshytip("hide")});$("#"+b.getAttribute("id")+"-tip").unbind("click");$("#"+b.getAttribute("id")+"-tip").click(function(a){a.stopPropagation()})}
function showMessage(a,b,c){clearTimeout(messageTimeout);$("#notification-bar").css("bottom","-100px");$("#notification-bar").show();var e=$("#gallery-map-panel").is(":visible")?"+=250px":"+=200px";$("#notification-bar").animate({bottom:e},300,function(){});$("#nb-title").html(a);$("#nb-subtitle").html("");""!=b&&$("#nb-subtitle").html(b);-1!=c&&(messageTimeout=setTimeout("hideMessage();",c))}function hideMessage(){$("#notification-bar").fadeOut()}function isLoggedIn(){return userID}
function setUserIDFromSessionCookie(){debug("> setUserIDFromSessionCookie()");debug("Checking to see if the user is logged in via his cookie.");if(null!=$.cookie("session_cookie")&&null!=$.cookie("userid_cookie")){var a=$.cookie("session_cookie"),b=$.cookie("userid_cookie");jQuery.ajax({url:"/check_session.php?user_id="+b+"&session_id="+a,success:function(a){a=eval(a);2==a.length?(userID=parseInt(b),userToken=a[1],userName=a[0],debug("Yes, the user ("+userName+") is logged in via his cookie and userID has been set to "+
userID)):userID=0},async:!1})}}function removeLogin(){debug("> removeLogin()");$("#login-email").val("");$("#login-password").val("");$("#change-email").val("");$("#change-current-password").val("");$("#change-new-password").val("");$("#login-button").poshytip("hide")}
function showResetPassword(){debug("> showResetPassword()");$(".signup-flow").hide();$("#reset-password-A1").find(".subtitle").html(userName);$("#photo-background").show();$("#top-bar").hide();$("#top-bar-welcome").show();showNoBar();$("#reset-password-A1").center().fadeIn();$("#reset-password").val("");$("#reset-password").focus()}
function showForgotPassword(){debug("> showForgotPassword()");$(".signup-flow").hide();$("#forgot-password-A1").center().fadeIn();""!=$("#login-email").val()?($("#forgot-email").val($("#login-email").val()),$("#forgot-password").focus()):$("#forgot-email").focus()}
function changePassword(){debug("> changePassword()");if(""==$("#reset-password").val())showMessage("Ummm...you didn't type in a new password.","Please type in a new password.",5E3);else{var a=$("#reset-password").data("token"),b=hex_sha256($("#reset-password").val());$("#reset-password").val("");jQuery.ajax({type:"GET",url:"/change_password.php?user_id="+userID+"&token="+a+"&new_password_hash="+b+"&latitude="+gbLat+"&longtitude="+gbLng,success:function(a){-1==parseInt(a)?showMessage("Something went wrong. Please contact founders@dealupa.com.",
"Sorry about that.",5E3):($("#photo-background").hide(),window.location.replace("/"))},async:!0})}}
function logout(){debug("> logout()");userID=0;userName="";fbIsValid()&&FB.logout(function(){});debug("XXXXXXXXXXXX DELETING SESSION COOKIE XXXXXXXXXXXX");debug("XXXXXXXXXXXX DELETING SESSION COOKIE XXXXXXXXXXXX");debug("XXXXXXXXXXXX DELETING SESSION COOKIE XXXXXXXXXXXX");$.cookie("session_cookie",null,{expires:1E3,path:"/"});$.cookie("userid_cookie",null,{expires:1E3,path:"/"});$("#saved-searches").empty();$("#top-bar-links").html("");$("#top-bar-user-id").html("");$("#login-button").show();$("#signup-button").show();
$("#logout-button").hide();"EMAIL"==view&&changeView("LIST");categoriesRank2DBDirtyBit=categoriesRank1DBDirtyBit=1}function removeWelcome(){debug("> removeWelcome(recordAsSignupDismissal)");$("#top-bar-welcome").hide();$("#top-bar").show();$("#photo-background").hide();$(".signup-flow").fadeOut();"LIST"==view&&showMapBar()}
function executeSearch(){debug("> executeSearch()");"MAP"!=view&&(view="LIST",changeView(view));query=$("#top-bar-search-box").val();$("#top-bar-search-box").select().focus();""!=query&&(debug("query! ["+query+"]"),$("#clear-search-button").show(),$("#sort-options").hide(),loadAndDisplay(),$("#top-bar-search-box").css("width","115px"),$("#clear-search-button").fadeIn(),pushState())}
function clearSearch(){debug("> clearSearch()");$("#search-box").val("");$("#top-bar-search-box").val("");$("#clear-search-button").hide();$("#sort-options").show();query="";debug("SETTING currNELng to -1 (2)");currNELng=-1;$("#top-bar-search-box").css("width","195px");$("#clear-search-button").hide()}
function showWelcome(a){debug("> showWelcome()");$("#top-bar").hide();$("#top-bar-welcome").show();$(".signup-flow").hide();showNoBar();a?$("#welcome-A1").find(".x").show():$("#welcome-A1").find(".x").hide();isLoggedIn()?jQuery.ajax({url:"/check_has_zipcode.php?user_id="+userID,success:function(a){parseInt(a)?(debug("We have a zipcode for this user. Hide the welcome screens and call load."),$("#photo-background").hide(),$(".signup-flow").hide(),load()):(debug("We don't have a zipcode for this user. Show the zipcode screen."),
showZipcodeScreen())},async:!1}):(debug("User is not logged [[showWelcome]]."),mpq.track("Welcome screen shown",{mp_note:"Direct load of site",Origin:"Direct load of site",UTM:utm}),"A1"==welcomeScreen&&($("#welcome-A1").center(),$("#photo-background").show(),$("#welcome-A1").fadeIn(),"Explorer"!=BrowserDetect.browser&&$("#signup-email").focus()))}
function slideUpWelcome(){debug("> slideUpWelcome()");100==welcomeScreen?debug(""):200==welcomeScreen?$("#welcome-200").slideDown():300==welcomeScreen?$("#welcome-300").slideDown():400<=welcomeScreen&&500>welcomeScreen&&debug("")}function setUserID(a){debug("> setUserID(fbID)");jQuery.ajax({type:"GET",url:"/lookup_userid.php?fb_id="+a,success:function(a){userID=parseInt(a);initLoggedIn()},async:!1})}
function sendNewPassword(){debug("> sendNewPassword()");var a=$("#forgot-email").val(),b="/mail_password.php?email="+a;""==a?showMessage("We've emailed you a link to reset your password.","",1E4):jQuery.ajax({type:"GET",url:b,success:function(a){var b=parseInt(a);-1==b?(showMessage("Looks like that email isn't registered.","<a href='javascript:void(0)' onclick='showWelcome();'>Sign up</a> for an account.",1E4),$("#forgot-email").val("").focus()):1==b&&(showMessage("We've emailed you a link to reset your password.",
"",1E4),showLogin());debug(a)},async:!0})}
function recordZipcode(){debug("> recordZipcode()");var a=$("#signup-zipcode").val();if(/(^\d{5}$)/.test(a)){var b="/update_user_data.php?user_id="+userID+"&zipcode="+a+"&token="+userToken;jQuery.ajax({type:"GET",url:b,success:function(b){if(0==parseInt(b))showMessage("Please enter a valid U.S. zip code.","",5E3),$("#signup-zipcode").val("").focus();else{debug("Zip code was recorded in the DB as "+a);var e=1;cityEdition!=parseInt(b)&&(userEdition=cityEdition=parseInt(b),e=0);mpq.track("Zip code successfully recorded",
{mp_note:"Zip code successfully recorded for userId "+userID+", edition "+cityEdition+", zipcode "+a,"GB Correct":e,UTM:utm,UserID:userID});showCategoryPreferencesScreen()}},async:!1});1==userEdition&&(b="/update_user_data.php?user_id="+userID+"&max_deal_distance=50&token="+userToken,jQuery.ajax({type:"GET",url:b,success:function(){}}))}else showMessage("Please enter a valid U.S. zip code.","",5E3),$("#signup-zipcode").val("").focus()}
function showZipcodeScreen(){debug("> showZipcodeScreen()");$(".signup-flow").fadeOut();$("#photo-background").show();mpq.track("Zip code screen shown",{mp_note:"Zip code screen shown",UTM:utm});$("#zipcode-A1").center();$("#zipcode-A1").fadeIn();$("#signup-zipcode").focus()}
function showLogin(a){a?$("#login-A1").find(".x").show():$("#login-A1").find(".x").hide();debug("> showLogin()");$("#top-bar-welcome").show();$("#top-bar").hide();showNoBar();$(".signup-flow").hide();$("#photo-background").show();$("#login-A1").center();$("#login-A1").fadeIn();""!=$("#login-email").val()&&($("#login-A1").find(".title").html("Have you signed up before?"),$("#login-password").focus())}
function showCategoryPreferencesScreen(){debug("> showCategoryPreferencesScreen()");$("#single-deal-view").hide();isLoggedIn()?($("#category-preferences-A1 .category-preference").each(function(){var a=parseInt($(this).attr("cat-id"));$(this).data("status","1");-1==getVisibleCategories().indexOf(a)?setTo0InCatPrefUI(this):-1!=categoriesRank2_DB().indexOf(a)&&setTo2InCatPrefUI(this);$(this).unbind("mouseenter").mouseenter(function(){$(this).poshytip({className:"tip-twitter",content:$(this).attr("description"),
showTimeout:1,alignTo:"target",alignX:"center",offsetY:5,allowTipHover:!1,fade:!1,slide:!1});$(this).poshytip("show")});$(this).unbind("mouseleave").mouseleave(function(){$(this).poshytip("hide");$(this).poshytip("destroy")})}),$(".signup-flow").hide(),$("#photo-background").hide(),$("#category-preferences-A1").show()):debug("ERROR in showCategoryPreferencesScreen: a non-logged-user should never see the category preferences screen!")}
function saveEmailSettings(){debug("> saveEmailSettings()");catsToDelete=[];catsToSetTo1=[];catsToSetTo2=[];$("#email .category-preference").each(function(){"0"==$(this).data("status")?catsToDelete.push(parseInt($(this).attr("cat-id"))):"1"==$(this).data("status")?catsToSetTo1.push(parseInt($(this).attr("cat-id"))):"2"==$(this).data("status")&&catsToSetTo2.push(parseInt($(this).attr("cat-id")))});updateCategories("DELETE",catsToDelete);updateCategories("SET_TO_1",catsToSetTo1);updateCategories("SET_TO_2",
catsToSetTo2);var a=$("#account-zipcode").val(),b=parseInt($("input:radio[name=account-frequency]:checked").val());maxDealDistance=parseInt($("#account-deal-distance").val());jQuery.ajax({type:"GET",url:"/update_user_data.php?user_id="+userID+"&user_edition="+userEdition+"&zipcode="+a+"&email_frequency="+b+"&max_deal_distance="+maxDealDistance+"&token="+userToken,success:function(b){0==parseInt(b)?(showMessage("Please enter a valid U.S. zipcode.","",5E3),$("#account-zipcode").val("").focus()):(debug("Zip code was recorded in the DB as "+
a),userEdition=cityEdition=parseInt(b),userZipCode=a,setNumberHidden(),changeView("LIST"),loadAndDisplay())},async:!1})}function unsubscribe(){jQuery.ajax({type:"GET",url:"/unsubscribe.php?user_id="+userID+"&token="+userToken,success:function(){""==$("#reset-password").val()&&showMessage("You've unsubscribed.","We're sorry to see you go.",5E3);$("#settings-unsubscribe").hide()},async:!1})}
function recordCategoryPreferences(){debug("> recordCategoryPreferences()");catsToDelete=[];catsToSetTo1=[];catsToSetTo2=[];$("#category-preferences-A1 .category-preference").each(function(){"0"==$(this).data("status")?catsToDelete.push(parseInt($(this).attr("cat-id"))):"1"==$(this).data("status")?catsToSetTo1.push(parseInt($(this).attr("cat-id"))):"2"==$(this).data("status")&&catsToSetTo2.push(parseInt($(this).attr("cat-id")))});updateCategories("DELETE",catsToDelete);updateCategories("SET_TO_1",
catsToSetTo1);updateCategories("SET_TO_2",catsToSetTo2);(0<catsToDelete.length||0<catsToDelete.length)&&mpq.track("User submitted category preferences during signup",{mp_note:"User submitted category preferences during signup, userId "+userID+", number of categories removed "+catsToDelete.length+", number of categories hearted "+catsToSetTo2.length,"Number deleted":catsToDelete.length,"Number hearted":catsToSetTo2.length,UTM:utm,UserID:userID});"undefined"!==typeof singleDeal.dealID?$("#single-deal-view").show():
(load(),setNumberHidden());removeWelcome()}function updateCategories(a,b){debug("> updateCategories(action, cats)");isLoggedIn()?updateCategories_DB(a,b):updateCategories_COOKIE(a,b)}function saveEdition(a){debug("> saveEdition(newEdition)");isLoggedIn()?saveEdition_DB(a):saveEdition_COOKIE(a)}
function getVisibleCategories(){if(isLoggedIn())return debug("from DB"),categoriesRank1_DB().concat(categoriesRank2_DB()).sort(function(a,b){return a-b});debug("from COOKIE");return categoriesRank1_COOKIE().concat(categoriesRank2_COOKIE()).sort(function(a,b){return a-b})}function isVisible(a){return-1!=getVisibleCategories().indexOf(a)?!0:!1}
function updateCategories_COOKIE(a,b){var c=categories_COOKIE();$.each(b,function(b,g){if("SET_TO_1"==a)-1==c.indexOf(g)&&c.push(g);else if("DELETE"==a){var e=c.indexOf(g);-1!=e&&c.splice(e,1)}});c.sort(function(a,b){return a-b});var e=$.cookie("last_view"),e=e.replace(/c=[^&]*/,"c="+c.toString());setLastViewCookie(e)}
function updateCategories_DB(a,b){categoriesRank2DBDirtyBit=categoriesRank1DBDirtyBit=1;"SET_TO_1"==a?a="categories_to_set_to_1":"DELETE"==a?a="categories_to_delete":"SET_TO_2"==a&&(a="categories_to_set_to_2");var c="/update_category_preferences.php?user_id="+userID+"&"+a+"="+JSON.stringify(b)+"&token="+userToken;jQuery.ajax({type:"GET",url:c,success:function(){},async:!1})}
function saveEdition_DB(a){jQuery.ajax({type:"GET",url:"/update_user_data.php?user_id="+userID+"&edition="+a,success:function(){},async:!1})}function saveEdition_COOKIE(a){var b=$.cookie("last_view"),b=b.replace(/i=[0-9]+/,"i="+a);setLastViewCookie(b)}
function setTo0InCatPrefUI(a){debug("> setTo0InCatPrefUI(elem)");$(a).data("status","0");$(a).find(".x").attr("src","/images/cat_x_on.png");$(a).find(".heart").attr("src","/images/cat_heart_off.png");$(a).find(".check").attr("src","/images/cat_check_off.png");$(a).find(".x-image").show();$(a).find(".heart-image").hide()}
function setTo1InCatPrefUI(a){debug("> setTo1InCatPrefUI(elem)");$(a).data("status","1");$(a).find(".x").attr("src","/images/cat_x_off.png");$(a).find(".heart").attr("src","/images/cat_heart_off.png");$(a).find(".check").attr("src","/images/cat_check_on.png");$(a).find(".x-image").hide();$(a).find(".heart-image").hide()}
function setTo2InCatPrefUI(a){debug("> setTo2InCatPrefUI(elem)");$(a).data("status","2");$(a).find(".x").attr("src","/images/cat_x_off.png");$(a).find(".heart").attr("src","/images/cat_heart_on.png");$(a).find(".check").attr("src","/images/cat_check_off.png");$(a).find(".x-image").hide();$(a).find(".heart-image").show()}function toggleInCatPrefUI(a){var b="setTo"+(parseInt($(a).data("status"))+1)%3+"InCatPrefUI";debug(b);window[b](a)}
function categoriesRank1_DB(){var a=[];categoriesRank1DBDirtyBit?(jQuery.ajax({type:"GET",url:"/get_categories.php?user_id="+userID+"&rank=1&token="+userToken,success:function(b){a=$.parseJSON(b)},async:!1}),categoriesRank1DBDirtyBit=0,categoriesRank1_DB_array=a.slice()):a=categoriesRank1_DB_array.slice();return a}function categoriesRank1_COOKIE(){cats=$.cookie("last_view").replace(/\?c=/,"").replace(/&.*/,"").split(",");$.each(cats,function(a,b){cats[a]=parseInt(b)});return cats}
function categoriesRank2_DB(){var a=[];categoriesRank2DBDirtyBit?(jQuery.ajax({type:"GET",url:"/get_categories.php?user_id="+userID+"&rank=2&token="+userToken,success:function(b){a=$.parseJSON(b)},async:!1}),categoriesRank2DBDirtyBit=0,categoriesRank2_DB_array=a.slice()):a=categoriesRank2_DB_array.slice();return a}function categoriesRank2_COOKIE(){return cats=[]}
function signupUser(){debug("> signupUser()");var a=$("#signup-email").val();if(validateEmail(a)){var b=(new Date).getTime();debug("UTM at time of signup: "+utm);jQuery.ajax({type:"GET",url:"/signup_user.php?email="+a+"&latitude="+gbLat+"&longitude="+gbLng+"&session_id="+b+"&utm="+utm+"&referrer="+referrer,success:function(c){debug("signupuser data: "+c);0==parseInt(c)?(mpq.track("Signup attempt with existing email",{mp_note:"Tried to sign up with "+a,City:cityEdition,UTM:utm}),showMessage("Looks like that email is already signed up. Please log in.",
"Forgot your password? <a onclick='showForgotPassword();' href='javascript:void(0);'>Reset it here</a>.",1E4),$("#login-email").val(a),showLogin()):-1!=parseInt(c)&&(c=eval(c),2==c.length&&(userToken=c[1],userID=c[0],debug("A new user record has been created. UserID is "+userID),mpq.track("User account created",{mp_note:"User account created with userID "+userID,City:cityEdition,UTM:utm}),$.cookie("session_cookie",b,{expires:1E3,path:"/"}),$.cookie("userid_cookie",userID,{expires:1E3,path:"/"}),initLoggedIn(),
showZipcodeScreen()))},async:!0})}else showMessage("Please enter a valid email address.","",5E3),$("#signup-email").val("").focus(),$("#signup-password").val("")}
function fbLogin(){debug("> fbLogin()");FB.login(function(a){debug("> FB.login callback");a.authResponse?(debug("Welcome!  Fetching your information.... "),debug("Calling FB.api to retrieve first, last, email, and Facebook ID."),FB.api("/me",function(a){urlString="/save_user.php?user_id="+a.id+"&first="+a.first_name+"&last="+a.last_name+"&email="+a.email+"&latitude="+gbLat+"&longitude="+gbLng;jQuery.ajax({url:urlString,success:function(a){a=eval(a);userToken=a[1];userID=a[0];login();initLoggedIn();
mpq.track("User manually logged in",{mp_note:"User manually logged in with Facebook account and userID "+userID,Type:"Facebook",UTM:utm,UserID:userID})},async:!1})})):debug("User cancelled login or did not fully authorize.")},{scope:"email"})}
function login(){debug("> login()");pushState();var a=(new Date).getTime();jQuery.ajax({type:"GET",url:"/update_user_session_id.php?user_id="+userID+"&session_id="+a+"&latitude="+gbLat+"&longitude="+gbLng,success:function(){$.cookie("session_cookie",a,{expires:1E7,path:"/"});$.cookie("userid_cookie",userID,{expires:1E7,path:"/"})},async:!1});$("#login-button").poshytip("hide");jQuery.ajax({url:"/check_has_zipcode.php?user_id="+userID,success:function(a){debug("check_has_zipcode says "+a);parseInt(a)?
($("#photo-background").hide(),$(".signup-flow").hide(),load()):showZipcodeScreen()},async:!1})}
function emailLogin(){debug("> emailLogin()");if(!(""==$("#login-email").val()||""==$("#login-password").val())){var a=hex_sha256($("#login-password").val()),a="email="+$("#login-email").val()+"&password_hash="+a;jQuery.ajax({type:"POST",url:"/login_user.php",data:a,success:function(a){debug(a);a=eval(a);2!=a.length?(showMessage("Oops, wrong password.","Forgot your password? <a onclick='showForgotPassword();' href='javascript:void(0);'>Reset it here</a>.",8E3),$("#login-password").val("").focus()):
(userToken=a[1],userID=a[0],debug("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"),debug("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"),debug("userToken: "+userToken),debug("userID: "+userID),debug("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"),debug("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"),$("#login-div-container").hide(),login(),initLoggedIn(),mpq.track("User manually logged in",{mp_note:"User manually logged in with Dealupa account and userID "+userID,Type:"Dealupa",UTM:utm,
UserID:userID}))},async:!0})}}function fbIsValid(){return"undefined"!==typeof FB}function createNewSendButton(a,b,c){if(fbIsValid()){var e=$(document.createElement("fb:like"));e.attr("href",b);e.attr("send","true");e.attr("layout",c);e.attr("show_faces","true");$(a).empty().append(e);FB.XFBML.parse($(a).get(0))}}function debug(a){debugging&&this.console&&"undefined"!=typeof console.log&&console.log(a)}function myConsoleTime(a){"Explorer"!=BrowserDetect.browser&&console.time(a)}
function myConsoleTimeEnd(a){"Explorer"!=BrowserDetect.browser&&console.timeEnd(a)}
function changeView(a){debug("> changeView(newView)");view=a;$("#single-category-back").hide();hideMessage();"MAP"==a?($("#refer-a-friend-area").hide(),$("#refer-a-friend").hide(),$("#map-list-toggle").show(),$("#map-view-toggle").addClass("down"),$("#list-view-toggle").removeClass("down"),$("#map").show(),$("#list-view-area").hide(),$("#right-bar").hide(),$("#filters-bar").show(),$("#single-deal-view").hide(),$("#email-settings").hide(),$("#hidden-categories").show(),google.maps.event.trigger(listMap,
"resize"),$("#list-view").empty(),changedEditionWhileInListView&&(map.setCenter(new google.maps.LatLng(cityLat[cityEdition],cityLng[cityEdition])),map.setZoom(cityZoom[cityEdition]),changedEditionWhileInListView=0),-1!=selectedMarkerIndex&&markerClick(markersArray[selectedMarkerIndex])(),resizeMap(),showNoMapBar(),40>getVisibleCategories().length&&setTimeout('showMessage("Want to see more deals?","Click \'Settings\' up top to adjust the kind of deals you see.",8000);',12E3)):"LIST"==a?($("#refer-a-friend-area").show(),
$("#map-list-toggle").show(),$("#map").hide(),$("#email").hide(),$("#right-bar").hide(),$("#refer-a-friend").hide(),$("#hidden-categories").show(),$("#list-view").show(),$("#list-view-num-deals").show(),$("#filters-bar").show(),$("#list-view-area").show(),""==query&&$("#sort-options").show(),$("#map-view-toggle").removeClass("down"),$("#list-view-toggle").addClass("down"),$("#city-name").html(cities[cityEdition].toLowerCase()),$("#single-deal-view").hide(),showMapBar(),initialLoadCompleted&&$("#container").masonry("reload")):
"SINGLE-CATEGORY"==a?($("#map-list-toggle").show(),$("#map").hide(),$("#email").hide(),$("#right-bar").hide(),$("#refer-a-friend-area").show(),$("#hidden-categories").hide(),$("#refer-a-friend").hide(),$("#single-category-back").show(),$("#list-view").show(),$("#list-view-num-deals").show(),$("#filters-bar").show(),$("#list-view-area").show(),""==query&&$("#sort-options").show(),$("#map-view-toggle").removeClass("down"),$("#list-view-toggle").addClass("down"),$("#city-name").html(cities[cityEdition].toLowerCase()),
$("#single-deal-view").hide(),showMapBar(),initialLoadCompleted&&$("#container").masonry("reload")):"SINGLE-DEAL"==a?($("#refer-a-friend-area").show(),$("#refer-a-friend-area").hide(),$("#refer-a-friend").hide(),$("#map-list-toggle").hide(),$("#single-deal-view").show(),$("#email").hide(),$("#map").hide(),$("#right-bar").hide(),$("#filters-bar").hide(),$("#list-view-area").hide(),$("#city-name").html(cities[cityEdition].toLowerCase()),showNoBar()):"EMAIL"==a?($("#email").show(),showNoBar(),$("#refer-a-friend-area").hide(),
$("#map-list-toggle").hide(),$("#refer-a-friend").hide(),$("#single-deal-view").hide(),$("#map").hide(),$("#right-bar").hide(),$("#filters-bar").hide(),$("#list-view-area").hide(),$("#city-name").html(cities[cityEdition].toLowerCase()),1==cityEdition&&($("#account-deal-distance").val("25"),$("#account-deal-distance option[value=0]").hide())):"REFER"==a&&($("#refer-a-friend").show(),showNoBar(),$("#refer-a-friend-area").hide(),$("#map-list-toggle").hide(),$("#email").hide(),$("#single-deal-view").hide(),
$("#map").hide(),$("#right-bar").hide(),$("#filters-bar").hide(),$("#list-view-area").hide(),$("#city-name").html(cities[cityEdition].toLowerCase()))}
function loadAndDisplayEmail(){debug("> loadAndDisplayEmail()");$(document).scrollTop(0);var a;jQuery.ajax({type:"GET",url:"/get_user_data.php?user_id="+userID+"&token="+userToken,success:function(b){a=$.parseJSON(b)},async:!1});$("#account-zipcode").val(a.zipcode);$("#account-deal-distance").val(a.max_deal_distance);debug("This user's frequency as recorded in DB: "+a.email_frequency);debug("This user's zip code as recorded in DB: "+a.zipcode);debug("This user's visible categories: "+getVisibleCategories());
$("#email .category-preference").each(function(){var a=parseInt($(this).attr("cat-id"));$(this).data("status","1");-1==getVisibleCategories().indexOf(a)?setTo0InCatPrefUI(this):-1!=categoriesRank2_DB().indexOf(a)&&setTo2InCatPrefUI(this);$(this).unbind("mouseenter").mouseenter(function(){$(this).poshytip({className:"tip-twitter",content:$(this).attr("description"),showTimeout:1,alignTo:"target",alignX:"center",offsetY:5,allowTipHover:!1,fade:!1,slide:!1});$(this).poshytip("show")});$(this).unbind("mouseleave").mouseleave(function(){$(this).poshytip("hide");
$(this).poshytip("destroy")})});604800==a.email_frequency?$("input[name=account-frequency]:eq(2)").attr("checked","checked"):259200==a.email_frequency?$("input[name=account-frequency]:eq(1)").attr("checked","checked"):$("input[name=account-frequency]:eq(0)").attr("checked","checked");showMessage("Here's where you decide what type of deals you'll see in your email and on the website.","",8E3)}
function selectFrequencyButton(a){$("#email .frequency-button").each(function(){$(this).removeClass("down")});$(a).addClass("down")}function updateFiltersUIBasedOnGlobals(){debug("> updateFiltersUIBasedOnGlobals()");setNumberHidden();setYelp(showYelp);$("#filter-company").val(showCompany)}
function loadAndDisplay(a){debug("> loadAndDisplay(doNotReloadList)");updateFiltersUIBasedOnGlobals();"MAP"==view?loadAndDisplayMarkers():"LIST"==view?(a||loadAndDisplayDeals(),$(document).scrollTop(0)):"SINGLE-CATEGORY"==view?loadAndDisplayDeals():"SINGLE-DEAL"==view?loadAndDisplaySingleDeal(mapViewDealID,cityEdition):"EMAIL"==view&&loadAndDisplayEmail()}
function applySlidersToListView(){debug("> applySlidersToListView()");for(var a=$("#container > div"),b=0;b<a.length;b++){var c=parseInt(a[b].getAttribute("id-at"));$("#slider-"+c).anythingSlider({hashTags:!1,buildArrows:!0,buildNavigation:!1,buildStartStop:!1,resizeContents:!1,autoPlay:!1,autoPlayLocked:!0,pauseOnHover:!0,resumeDelay:3E3})}}
function loadAndDisplayDeals(a){debug("> loadAndDisplayDeals(appendItems)");a||(pages=1);("LIST"==view||"SINGLE-CATEGORY"==view)&&""==query?(dealXML="/deal_html_from_url_params.php"+currentStateAsString()+"&p="+pages,"DISTANCE"==currentSortBy&&(dealXML+="&z="+zip),dealXML+="&uz="+userZipCode):"LIST"==view&&""!=query&&(dealXML="/deal_html_from_url_params.php"+currentStateAsString()+"&p="+pages,dealXML+="&uz="+userZipCode);debug(dealXML);a||$("#loading-div").center().show();jQuery.ajax({type:"GET",
url:dealXML,success:function(b){a||$("#container").empty();var c=$(b);c.imagesLoaded(function(){var a=$("#container");c.find("img.deal-image").each(function(){if(this.width!=229){this.style.width=columnWidth+"px";this.style.height="auto"}});a.append(c).masonry("appended",c);a.masonry({itemSelector:".box",gutterWidth:columnSpacing,isAnimated:false,isFitWidth:true});a.css({overflow:"visible"});a.find(".box").each(function(){$(this).removeClass("box-focus");$(this).find(".expansion").hide()});a.masonry("reload");
a=parseInt($("#list-view-data").attr("num-deals"));if(maxDealDistance==0||cityEdition!=userEdition)$("#list-view-sorted-by").html(" - "+a+" deals");else{var b="";maxDealDistance>1&&(b="s");$("#list-view-sorted-by").html(" - "+a+" deals within <b><a href='javascript:void(0);' onclick='changeView(\"EMAIL\"); loadAndDisplayEmail(); pushState();'>"+maxDealDistance+" mile"+b+" </a></b> of "+userZipCode)}registerListViewCallBacks();$("#loading-div").hide();setTimeout("infiniteScrollTimeout = 1",100);google.maps.event.trigger(listMap,
"resize");$("#loading-div").center().hide()})},async:!0})}
function expandDeal(){clearTimeout(galleryMapTimeout);$("#gallery-map-container").stop().css("opacity","1.0");var a=parseInt($(this).closest(".top-div").attr("id-at"));$(this).addClass("box-focus");$(this).find(".expansion").show();$("#fb-buttons-"+a).hide();var b=this.getAttribute("lat-at"),c=this.getAttribute("lng-at");""!=b?(debug("lat: "+b+" lng: "+c),listMap.setCenter(new google.maps.LatLng(b,c)),listMarker.position=new google.maps.LatLng(b,c),listMarker.setMap(listMap),$("#gallery-map-container").show(),
google.maps.event.trigger(listMap,"resize")):$("#gallery-map-container").hide();b=$(this).closest(".top-div").attr("url-at");b="http://dealupa.com"+b;35>$("#fb-buttons-"+a).html().length&&createNewSendButton("#fb-buttons-"+a,b+"?utm=facebook_share","button_count");$("#fb-buttons-"+a).fadeIn()}function collapseDeal(){$(this).removeClass("box-focus");$(this).find(".expansion").hide();galleryMapBlocker||(galleryMapTimeout=setTimeout('$("#gallery-map-container").fadeOut()',750))}
function showNoMapBar(){debug("> showNoMapBar()");$("#gallery-map-panel").hide();$("#bottom-bar").show()}function showMapBar(){debug("> showMapBar()");$("#gallery-map-panel").show();$("#bottom-bar").show();google.maps.event.trigger(listMap,"resize")}function showNoBar(){debug("> showNoBar()");$("#gallery-map-panel").hide();$("#bottom-bar").hide()}
function registerListViewCallBacks(){debug("> registerListViewCallBacks()");for(var a=$("#container > div"),b=0;b<a.length;b++){var c=a[b];c.getAttribute("lat-at");c.getAttribute("lng-at");var e=c.getAttribute("id-at");c.getAttribute("cat-at");c.getAttribute("cmp-at");c.getAttribute("y-at");c.getAttribute("p-at");c.getAttribute("v-at");var f={over:expandDeal,out:collapseDeal};$(c).unbind("mouseenter").unbind("mouseleave");$(c).hoverIntent(f);$(c).find("#details-"+e).unbind("click").click(function(){var a=
parseInt($(this).closest(".top-div").attr("id-at")),b=$(this).closest(".top-div").attr("cat-at"),c=$(this).closest(".top-div").attr("cmp-at"),e=parseFloat($(this).closest(".top-div").attr("y-at")),f=parseInt($(this).closest(".top-div").attr("p-at")),l=parseInt($(this).closest(".top-div").attr("v-at"));mpq.track("Clicked to external deal site",{mp_note:"Clicked on "+a+", company "+companies[c],Company:companies[parseInt(c)],Category:categories[parseInt(b)],Yelp:e,City:cities[cityEdition],Price:f,Value:l,
View:"LIST-button",Sort:currentSortBy,UserID:userID})});$(c).find("#image-link-"+e).unbind("click").click(function(){var a=parseInt($(this).closest(".top-div").attr("id-at")),b=$(this).closest(".top-div").attr("cat-at"),c=$(this).closest(".top-div").attr("cmp-at"),e=parseFloat($(this).closest(".top-div").attr("y-at")),f=parseInt($(this).closest(".top-div").attr("p-at")),l=parseInt($(this).closest(".top-div").attr("v-at"));mpq.track("Clicked to external deal site",{mp_note:"Clicked on "+a+", company "+
companies[c],Company:companies[parseInt(c)],Category:categories[parseInt(b)],Yelp:e,City:cities[cityEdition],Price:f,Value:l,View:"LIST-image",Sort:currentSortBy,UserID:userID})})}"LIST"==view?""==query?2==cityEdition?$("#list-view-num-deals").html("Nationwide deals"):1!=cityEdition?$("#list-view-num-deals").html("Deals in "+cities[cityEdition]):$("#list-view-num-deals").html("Deals near "+userZipCode):""!=query&&$("#list-view-num-deals").html("Deals for <b>"+query+"</b> in "+cities[cityEdition]):
"SINGLE-CATEGORY"==view&&($("#list-view-num-deals").html(categories[singleCategory]+" deals in "+cities[cityEdition]),$("#single-category-back").html("&#171; Back to all deals in "+cities[cityEdition]));"SOLD"==currentSortBy?sortByString="number sold":sortByString=currentSortBy.toLowerCase();$("#sort"+currentSortBy).addClass("sort-on")}
function showSingleCategory(a){changeView("SINGLE-CATEGORY");$(document).scrollTop(0);singleCategory=a;loadAndDisplay();pushState();showMessage("These are <i>just</i>&nbsp;&nbsp;the "+categories[a]+" deals.","Go back to <a href='javascript:void(0);' onclick='changeView(\"LIST\");loadAndDisplay(0);pushState();'>all deals</a> in "+cities[cityEdition]+".",2E4)}
function openDealInSingleDealView(a,b){debug("> openDealInSingleDealView(dealToDisplay, edition)");listScrollPosition=$(document).scrollTop();mapViewDealID=a;changeView("SINGLE-DEAL");loadAndDisplaySingleDeal(a,b)}
function singleDealPostProcessing(){debug("> singleDealPostProcessing()");$("#slider").imagesLoaded(function(){$("#slider").anythingSlider({hashTags:!1,buildArrows:!0,buildNavigation:!1,buildStartStop:!1,resizeContents:!1,autoPlay:!0,autoPlayLocked:!0,pauseOnHover:!0,resumeDelay:1E3});$("#single-deal-left").css({opacity:1})});singleDeal.maintitle=$("#single-deal-data").attr("title");singleDeal.dealID=$("#single-deal-data").attr("deal_id");singleDeal.categoryID=$("#single-deal-data").attr("category_id");
singleDeal.imageUrls=eval($("#single-deal-data").attr("image_arr_str"));singleDeal.edition=eval($("#single-deal-data").attr("deal_edition"));singleDeal.cities=eval($("#single-deal-data").attr("cities_arr_str"));singleDeal.lats=eval($("#single-deal-data").attr("lats_arr_str"));singleDeal.lngs=eval($("#single-deal-data").attr("lngs_arr_str"));singleDeal.fullUrl=$("#single-deal-data").attr("full_url");$("#city-name").html(cities[cityEdition].toLowerCase());$(document).scrollTop(0)}
function loadAndDisplaySingleDeal(a,b){debug("> loadAndDisplaySingleDeal(dealIDToDisplay, edition)");var c=selectedMarkerImageIndex=0;if(initialLoadCompleted){if(null==document.getElementById("image-"+a)){var e;jQuery.ajax({type:"GET",url:"/is_landscape.php?ajax&deal_id="+a,success:function(a){c=parseInt(a)},async:!1})}else{e=document.getElementById("image-"+a).width;var f=document.getElementById("image-"+a).height;1<e/f&&(c=1)}c?(debug("LANDSCAPE SINGLE DEAL"),e="/single_deal_html_landscape.php?logged_in=1&m="+
a+"&i="+b):(debug("PORTRAIT SINGLE DEAL"),e="/single_deal_html_portrait.php?logged_in=1&m="+a+"&i="+b);jQuery.ajax({type:"GET",url:e,success:function(a){$("#single-deal-view").html(a);singleDealPostProcessing()},async:!1})}else singleDealPostProcessing(),debug("Returning from loadAndDisplaySingleDeal because the HTML is in the index.php file")}
function currentStateAsString(){debug("> currentStateAsString()");var a;"SINGLE-DEAL"==view&&(a="?m="+mapViewDealID+"&i="+cityEdition+"&v="+view);"SINGLE-CATEGORY"==view&&(a="?c="+singleCategory+"&y="+showYelp+"&i="+cityEdition+"&v="+view+"&s="+currentSortBy+"&d="+maxDealDistance);"LIST"==view&&(a="?c="+getVisibleCategories()+"&y="+showYelp+"&o="+showCompany+"&i="+cityEdition+"&e="+userEdition+"&v="+view+"&s="+currentSortBy+"&d="+maxDealDistance,"DISTANCE"==currentSortBy&&(a+="&z="+zip));"MAP"==view&&
(a="?t="+trueRound(map.getCenter().lat(),4)+"&g="+trueRound(map.getCenter().lng(),4)+"&z="+map.getZoom()+"&c="+getVisibleCategories()+"&y="+showYelp+"&o="+showCompany+"&v="+view+"&m="+mapViewDealID+"&d="+maxDealDistance);"EMAIL"==view&&(a="?v="+view+"&u="+userID);if(""!=query&&("MAP"==view||"LIST"==view))a+="&q="+query;return a}function findMarkersArrayIndex(a){for(var b=0;b<markersArray.length;b++)if(markersArray[b].dealID==a)return b;return-1}
function parseStateString(a){debug("> parseStateString(params)");var b=getParameter("i",a);getParameter("c",a);var c=getParameter("v",a),e=getParameter("m",a),f=getParameter("q",a),g=getParameter("w",a),a=getParameter("utm",a);"null"!=b&&(cityEdition=/^[0-9]+$/.test(b)?parseInt(b):null!=citiesReverse[b]?citiesReverse[b]:calculateCityEditionFromLatLng(gbLat,gbLng),map.setZoom(parseInt(cityZoom[cityEdition])),map.setCenter(new google.maps.LatLng(cityLat[cityEdition],cityLng[cityEdition])));"null"!=
c&&(view=c);"null"!=e&&(mapViewDealID=parseInt(e));f!=query&&!("null"==f&&""==query)&&(currNELng=-1);query="";"null"!=f&&null==categoriesReverse[f]&&(query=f,query=query.replace(/-/g," "),$("#top-bar-search-box").css("width","115px"),$("#top-bar-search-box").val(query),$("#clear-search-button").show());"null"==c&&"null"!=e&&(view="SINGLE-DEAL");"null"!=g&&(welcomeScreen=g);"null"!=a&&(utm=a+"_"+welcomeScreen)}
function setLastViewCookie(a){debug("> setLastViewCookie(newCookieValue)");debug("Setting the value of the last_view cookie to: "+a);$.cookie("last_view",a,{expires:1E3,path:"/"});$.cookie("timestamp",(new Date).getTime(),{expires:1E3,path:"/"})}
function initLoggedIn(){debug("> initLoggedIn()");$("#top-bar-links").html("<a href='javascript:void(0);' onclick='changeView(\"EMAIL\"); loadAndDisplayEmail(); pushState();'>Settings</a>");categoriesRank2DBDirtyBit=categoriesRank1DBDirtyBit=1;jQuery.ajax({url:"/get_email.php?user_id="+userID+"&token="+userToken,success:function(a){$("#top-bar-user-id").html(a);userName=a},async:!1});$("#login-button").poshytip("hide");$("#login-div-container").hide();$("#login-button").hide();$("#signup-button").hide();
$("#logout-button").show();$("#login-password").val("");jQuery.ajax({url:"/update_user.php?user_id="+userID,success:function(){debug("User's visit count, last seen date, and session created date have been update in the DB [[initLoggedIn]].")},async:!1})}function clearYelp(){$("#yelp-reviews").hide()}function clearYelpList(){$("#list-yelp-reviews").hide()}function getParameter(a,b){return decodeURI((RegExp("[?|&]"+a+"=(.+?)(&|$)").exec(b)||[,null])[1])}
function changeEdition(a){debug("> changeEdition(newEdition)");"MAP"!=view&&(view="LIST",changeView(view));isLoggedIn()||saveEdition(a);currentSortBy="SOLD";highlightSortLink();$("#dealupa-title").poshytip("hide");cityEdition=a;$("#city-name").html(cities[cityEdition].toLowerCase());$("#list-view-num-deals").html("Loading deals in "+cities[cityEdition]+"...");$("#list-view-sorted-by").empty();"LIST"==view?(changedEditionWhileInListView=1,loadAndDisplay()):"MAP"==view?(map.setZoom(cityZoom[cityEdition]),
map.setCenter(new google.maps.LatLng(cityLat[cityEdition],cityLng[cityEdition]))):"SINGLE-DEAL"==view?(map.setCenter(new google.maps.LatLng(cityLat[cityEdition],cityLng[cityEdition])),changeView("LIST"),loadAndDisplay()):"SINGLE-CATEGORY"==view&&(view="LIST",loadAndDisplay())}function getSingleDealURLRelative(a,b,c){return"/"+cities_url[a]+"/daily-deals/"+b+"-"+hyphenateTitle(c)}function getSingleDealURLFull(a,b,c){a=getSingleDealURLRelative(a,b,c);return"http://dealupa.com"+a}
function pushState(){var a={stateParams:currentStateAsString()};debug("*********** PUSH ************");debug(currentStateAsString());debug("*****************************");if("Explorer"!=BrowserDetect.browser){if("SINGLE-DEAL"==view){var b=getSingleDealURLRelative(singleDeal.edition,singleDeal.dealID,singleDeal.maintitle);history.pushState(a,"",b)}else history.pushState(a,"","/");historyObject.push(a)}}
function hyphenateTitle(a){a=a.toLowerCase();a=a.replace(/\b[a-z]\b/g,"");a=a.replace(/\b[a-z][a-z]\b/g,"");a=a.replace(/[0-9] (value|regular)\b/g,"");a=a.replace(/[0-9] (towards|spend)\b/g,"");a=a.replace(/\b(for|the|and|are|but|you|reg|your|more)\b/g,"");a=a.replace(/&[0-9a-z]+;/g,"-");a=a.replace(/[^a-z0-9\-]/g,"-");a=a.replace(/\b[0-9]+\b/g,"-");a=a.replace(/ /g,"-");a=a.replace(/-+/g,"-");a=a.replace(/deal-ends-soon/g,"");a=a.replace(/^-/g,"");a=a.replace(/-$/g,"");""==a&&(a="deal");return a}
function referAFriend(){var a=[],b=$("#email-text").val();$("#refer-inputs").children().each(function(){validateEmail($(this).val())&&a.push($(this).val())});debug(JSON.stringify(a));b="/refer_a_friend.php?user_id="+userID+"&emails="+JSON.stringify(a)+"&email_text="+b+"&token="+userToken;jQuery.ajax({type:"GET",url:b,success:function(a){0<eval(a).length&&(changeView("LIST"),showMessage("Nice, you've invited your friends.","Thanks for spreading the word about Dealupa!",5E3),loadAndDisplay())},async:!1})}
function resizeMap(){$("#map").height($(window).height()-$("#top-bar").outerHeight());$(".signup-flow.wooden").each(function(){$(this).center()});$("#loading-div").center();$("#popup-refer-a-friend").center();if("undefined"!==typeof map.getCenter){var a=map.getCenter().lat(),b=map.getCenter().lng();google.maps.event.trigger(map,"resize");""!=a&&""!=b&&map.setCenter(new google.maps.LatLng(a,b))}a=numPerColumnBig*columnWidth+(numPerColumnBig-1)*columnSpacing;b=numPerColumnSmall*columnWidth+(numPerColumnSmall-
1)*columnSpacing;1300<$(window).width()?($("#list-view-area").css("width",a+"px"),$("#refer-a-friend-area").css("width",a+"px"),$("#bottom-bar-content").css("margin-left",a/-2+"px"),$("#top-bar-content").css("width",a+"px"),$("#bottom-bar-content").css("width",a+"px")):($("#list-view-area").css("width",b+"px"),$("#refer-a-friend-area").css("width",b+"px"),$("#bottom-bar-content").css("margin-left",b/-2+"px"),$("#top-bar-content").css("width",b+"px"),$("#bottom-bar-content").css("width",b+"px"));$("#top-bar-content-table").show();
$("#bottom-bar-content").show()}function selectOnMap(a){a=findDealInMarkersArray(a);changeView("MAP");markerClick(markersArray[a])();map.panTo(new google.maps.LatLng(markersArray[a].position.lat(),markersArray[a].position.lng()))}function findDealInMarkersArray(a){for(i in markersArray)if(markersArray[i].dealID==a)return i}
function showNextImage(){selectedMarkerImageIndex=(selectedMarkerImageIndex+1)%markersArray[selectedMarkerIndex].imageUrls.length;$("#left-image").attr("src",markersArray[selectedMarkerIndex].imageUrls[selectedMarkerImageIndex])}function showPrevImage(){var a=markersArray[selectedMarkerIndex].imageUrls.length;selectedMarkerImageIndex=(selectedMarkerImageIndex-1+a)%a;$("#left-image").attr("src",markersArray[selectedMarkerIndex].imageUrls[selectedMarkerImageIndex])}
function showNextImageSingle(){selectedMarkerImageIndex=(selectedMarkerImageIndex+1)%singleDeal.imageUrls.length;$("#single-image").attr("src",singleDeal.imageUrls[selectedMarkerImageIndex])}function showPrevImageSingle(){var a=singleDeal.imageUrls.length;selectedMarkerImageIndex=(selectedMarkerImageIndex-1+a)%a;$("#single-image").attr("src",singleDeal.imageUrls[selectedMarkerImageIndex])}
function loadAndDisplayMarkers(){debug("> loadAndDisplayMarkers()");var a=map.getBounds();if(null!=a){var b=a.getSouthWest(),c=a.getNorthEast();if(-1!=currNELng&&currSWLat<b.lat()&&currSWLng<b.lng()&&c.lat()<currNELat&&c.lng()<currNELng&&""==query)displayMarkers(),debug("--returning without reloading markers 2");else{var a=b.lat()-(c.lat()-b.lat()),e=b.lng()-(c.lng()-b.lng()),f=c.lat()+(c.lat()-b.lat()),b=c.lng()+(c.lng()-b.lng()),c="/marker_xml.php?swLat="+a+"&swLng="+e+"&neLat="+f+"&neLng="+b;""!=
query&&(c+="&q="+query);debug("reloading markers: "+c);$("#loading-div").center().show();jQuery.ajax({url:c,success:function(a){selectedMarkerIndex=0;deleteOverlays(markersArray);debug("Deleted markersArray, whose length is now "+markersArray.length);for(var a=a.documentElement.getElementsByTagName("marker"),b={},c=0;c<a.length;c++){var e=trueRound(a[c].getAttribute("latitude"),2),f=trueRound(a[c].getAttribute("longitude"),2),e=a[c].getAttribute("company_id")+":"+e+":"+f+":"+a[c].getAttribute("title");
if(!(""!=a[c].getAttribute("title")&&b.hasOwnProperty(e))){b[e]=1;e=new google.maps.LatLng(parseFloat(a[c].getAttribute("latitude")),parseFloat(a[c].getAttribute("longitude")));f=""==a[c].getAttribute("yelp_rating")?-1:parseFloat(a[c].getAttribute("yelp_rating"));e=new google.maps.Marker({dealID:parseInt(a[c].getAttribute("id")),address_id:parseInt(a[c].getAttribute("address_id")),position:e,icon:eval("marker0"),categoryIDs:[],index:markersArray.length,maintitle:a[c].getAttribute("title"),subTitle:a[c].getAttribute("subtitle"),
subTitle:a[c].getAttribute("subtitle"),name:a[c].getAttribute("name"),street:a[c].getAttribute("street"),city:a[c].getAttribute("city"),state:a[c].getAttribute("state"),zip:a[c].getAttribute("zip"),price:parseInt(a[c].getAttribute("price")),numPurchased:a[c].getAttribute("num_purchased"),value:a[c].getAttribute("value"),discount:Math.round(100*(parseFloat(a[c].getAttribute("value"))-parseFloat(a[c].getAttribute("price")))/parseFloat(a[c].getAttribute("value"))),savings:parseFloat(a[c].getAttribute("value"))-
parseFloat(a[c].getAttribute("price")),dealUrl:a[c].getAttribute("url"),affiliateUrl:a[c].getAttribute("affiliate_url"),deadline:a[c].getAttribute("deadline"),discovered:a[c].getAttribute("discovered"),imageUrls:[],website:a[c].getAttribute("website"),upcoming:a[c].getAttribute("upcoming"),expired:a[c].getAttribute("expired"),age:getAge(mysqlTimeStampToDate(a[c].getAttribute("discovered"))),companyID:a[c].getAttribute("company_id"),yelpRatingStr:f.toString(),yelpUrl:a[c].getAttribute("yelp_url"),
yelpCount:a[c].getAttribute("yelp_review_count"),yelpUser:[a[c].getAttribute("yelp_user1"),a[c].getAttribute("yelp_user2"),a[c].getAttribute("yelp_user3")],yelpUserUrl:[a[c].getAttribute("yelp_user_url1"),a[c].getAttribute("yelp_user_url2"),a[c].getAttribute("yelp_user_url3")],yelpUserPhoto:[a[c].getAttribute("yelp_user_image_url1"),a[c].getAttribute("yelp_user_image_url2"),a[c].getAttribute("yelp_user_image_url3")],yelpUserExcerpt:[a[c].getAttribute("yelp_excerpt1"),a[c].getAttribute("yelp_excerpt2"),
a[c].getAttribute("yelp_excerpt3")],yelpReviewUrl:[a[c].getAttribute("yelp_review_url1"),a[c].getAttribute("yelp_review_url2"),a[c].getAttribute("yelp_review_url3")],yelpUserRating:[a[c].getAttribute("yelp_rating1"),a[c].getAttribute("yelp_rating2"),a[c].getAttribute("yelp_rating3")]});markersArray.push(e);var f=a[c].childNodes,l=-1;e.icon=eval("marker0");for(var k=0;k<f.length;k++)if("category"==f[k].nodeName)categoryId=parseInt(f[k].getAttribute("category_id")),categoryRank=parseInt(f[k].getAttribute("rank")),
e.categoryIDs.push(categoryId),categoryRank>l&&(l=categoryRank,e.icon=eval("marker"+categoryIDToSetID[categoryId]));else if("image"==f[k].nodeName){var m=f[k].getAttribute("image_url");e.imageUrls.push(m)}0==e.categoryIDs.length&&e.categoryIDs.push(0);0==e.imageUrls.length&&e.imageUrls.push("")}}selectedMarkerIndex=findMarkersArrayIndex(mapViewDealID);-1==selectedMarkerIndex&&(selectedMarkerIndex=0);highlightSelectedMarker(markersArray[selectedMarkerIndex]);markerClick(markersArray[selectedMarkerIndex])();
displayMarkers();$("#loading-div").hide()},async:!0});currSWLat=a;currSWLng=e;currNELat=f;currNELng=b}}else debug("--returning without reloading markers 1")}
function displayMarkers(){debug("> displayMarkers()");for(var a=0;a<markersArray.length;a++)isVisible(markersArray[a].categoryIDs[0])?0!=showYelp&&showYelp>parseFloat(markersArray[a].yelpRatingStr)?markersArray[a].setMap(null):0!=showCompany&&showCompany!=markersArray[a].companyID?markersArray[a].setMap(null):null==markersArray[a].getMap()&&(markersArray[a].setMap(map),google.maps.event.addListener(markersArray[a],"click",markerClick(markersArray[a])),google.maps.event.addListener(markersArray[a],
"mouseover",markerOver(markersArray[a])),google.maps.event.addListener(markersArray[a],"mouseout",markerOut(markersArray[a]))):markersArray[a].setMap(null)}
var markerClick=function(a){return function(){$("#right-bar").hide();jQuery.ajax({url:"/deal_html_from_deals_index.php?map_view&deal_id="+a.dealID+"&edition="+cityEdition,success:function(b){var c=markersArray[selectedMarkerIndex].categoryIDs[0];markersArray[selectedMarkerIndex].setIcon(new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(13,13),new google.maps.Point(0+13*categoryIDToSetID[c],0),new google.maps.Point(6,6)));mapViewDealID=parseInt(a.dealID);$("#right-bar").html(b);
$("#right-bar").find("img.deal-image").hide();$("#right-bar").find("div.subtitle").show();$("#right-bar").imagesLoaded(function(){$("#right-bar").find("img.deal-image").each(function(){310>this.width&&(this.style.width="310px",this.style.height="auto");"MAP"==view&&($("#right-bar").find("img.deal-image").show(),$("#right-bar").show())})});selectedMarkerIndex=a.index;markersArray[selectedMarkerIndex].setIcon(new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(19,19),new google.maps.Point(169+
19*categoryIDToSetID[a.categoryIDs[0]],0),new google.maps.Point(9,9)));$("#right-bar").find("#image-link-"+mapViewDealID).unbind("click").click(function(){parseInt($(this).closest(".top-div").attr("id-at"));$(this).closest(".top-div").attr("cat-at");$(this).closest(".top-div").attr("cmp-at");parseFloat($(this).closest(".top-div").attr("y-at"));var b=parseInt($(this).closest(".top-div").attr("p-at")),c=parseInt($(this).closest(".top-div").attr("v-at"));mpq.track("Clicked to external deal site",{mp_note:"Clicked on "+
mapViewDealID+", company "+a.companyID,Company:companies[a.companyID],Category:categories[a.categoryIDs[0]],Yelp:parseFloat(a.yelpRatingStr),City:cities[cityEdition],Price:b,Value:c,View:"MAP-image",UserID:userID})});$("#right-bar").find("#details-"+mapViewDealID).unbind("click").click(function(){parseInt($(this).closest(".top-div").attr("id-at"));$(this).closest(".top-div").attr("cat-at");$(this).closest(".top-div").attr("cmp-at");parseFloat($(this).closest(".top-div").attr("y-at"));var b=parseInt($(this).closest(".top-div").attr("p-at")),
c=parseInt($(this).closest(".top-div").attr("v-at"));mpq.track("Clicked to external deal site",{mp_note:"Clicked on "+mapViewDealID+", company "+a.companyID,Company:companies[a.companyID],Category:categories[a.categoryIDs[0]],Yelp:parseFloat(a.yelpRatingStr),City:cities[cityEdition],Price:b,Value:c,View:"MAP-button",UserID:userID})});$(".expansion").show()},async:!0})}},markerOut=function(){return function(){$("#hover-info").hide();$("#hover-info-image").attr("src","")}},markerOver=function(a){return function(){var b=
Math.pow(2,map.getZoom()),c=new google.maps.LatLng(map.getBounds().getNorthEast().lat(),map.getBounds().getSouthWest().lng()),c=map.getProjection().fromLatLngToPoint(c),e=map.getProjection().fromLatLngToPoint(a.getPosition()),b=new google.maps.Point(Math.floor((e.x-c.x)*b),Math.floor((e.y-c.y)*b));350>$(window).width()-b.x?$("#hover-info").css("left",b.x-381):$("#hover-info").css("left",b.x+20);$("#hover-info").css("top",b.y-30);$("#hover-info-maintitle").html(a.maintitle);0==a.subTitle.length?$("#hover-info-subtitle").hide():
($("#hover-info-subtitle").show(),$("#hover-info-subtitle").html(a.subTitle));$("#hover-info-company").html(companies[a.companyID]);"-1"==a.yelpRatingStr?$("#hover-info-yelp").hide():($("#hover-info-yelp").show(),$("#hover-info-yelp-stars").attr("src","/images/yelp/yelp_"+a.yelpRatingStr.replace(".","")+".png"),$("#hover-info-yelp-count").html(" - "+a.yelpCount+" reviews"));$("#hover-info").show();$("#hover-info-image").hide();debug(a.imageUrls[0]);$("#hover-info-image").attr("src",a.imageUrls[0]+
"?"+(new Date).getTime());var f,g,h;$("<img/>").attr("src",$("#hover-info-image").attr("src")+"?"+(new Date).getTime()).load(function(){f=this.width;g=this.height;h=f/g;parseFloat(h)>1.32941176?$("#hover-info-image").animate({height:"85px"},1,function(){$("#hover-info-image").show()}):$("#hover-info-image").animate({width:"113px"},1,function(){$("#hover-info-image").show()})})}};
function resortListView(a){debug("> resortListView(newSortBy)");"DISTANCE"==a&&""==$("#sort-zip").val()||("DISTANCE"==a&&(zip=$("#sort-zip").val(),$.cookie("zip_cookie",zip,{expires:1E3,path:"/"})),currentSortBy=a,highlightSortLink(),loadAndDisplay(),"SOLD"==currentSortBy?sortByString="number sold":sortByString=currentSortBy.toLowerCase(),pushState())}
function highlightSortLink(){debug("> highlightSortLink()");$("#sortNEW").removeClass("sort-on");$("#sortSOLD").removeClass("sort-on");$("#sortPRICE").removeClass("sort-on");$("#sortDEADLINE").removeClass("sort-on");$("#sortDISTANCE").removeClass("sort-on");$("#sort"+currentSortBy).addClass("sort-on")}function indexOfFirstVisibleDeal(a,b){for(var c=0;c<a.length;c++)if($("#"+b+"list-view-id-"+c).is(":visible"))return c}
function deleteOverlays(a){debug("> deleteOverlays(arr)");if(0<a.length){for(var b=0;b<a.length;b++)a[b].setMap(null);a.length=0}}function mysqlTimeStampToDate(a){a=a.replace(/^([0-9]{2,4})-([0-1][0-9])-([0-3][0-9]) (?:([0-2][0-9]):([0-5][0-9]):([0-5][0-9]))?$/,"$1 $2 $3 $4 $5 $6").split(" ");return new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5])}
function isExpired(a){d=new Date;var b=new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours(),d.getUTCMinutes(),d.getUTCSeconds(),d.getUTCMilliseconds());timeNow=new Date;differenceInMilliseconds=a.getTime()-b.getTime();delete timeNow;return 0>differenceInMilliseconds?1:0}
function getAge(a){d=new Date;var b=new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours(),d.getUTCMinutes(),d.getUTCSeconds(),d.getUTCMilliseconds());timeNow=new Date;differenceInMilliseconds=b.getTime()-a.getTime();delete timeNow;return Math.floor(differenceInMilliseconds/864E5)}
function fillInAvailabilityInfo(a,b,c,e){d=new Date;var f=new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours(),d.getUTCMinutes(),d.getUTCSeconds(),d.getUTCMilliseconds());timeNow=new Date;differenceInMilliseconds=mysqlTimeStampToDate(a).getTime()-f.getTime();delete timeNow;1==b?document.getElementById(e).innerHTML="<span style='color:#659829;font-weight:700'>UPCOMING DEAL</span>":0>differenceInMilliseconds?document.getElementById(e).innerHTML="<span style='color:#a20000;font-weight:700'>EXPIRED</span>":
1==c?document.getElementById(e).innerHTML="<span style='color:#a20000;font-weight:700'>EXPIRED</span>":""==a?document.getElementById(e).innerHTML="This deal is currently available":(secs=mins=hours=days=0,out="Time left: <span class='expires-in'>",differenceInMilliseconds=Math.floor(differenceInMilliseconds/1E3),days=Math.floor(differenceInMilliseconds/86400),differenceInMilliseconds%=86400,hours=Math.floor(differenceInMilliseconds/3600),differenceInMilliseconds%=3600,mins=Math.floor(differenceInMilliseconds/
60),differenceInMilliseconds%=60,secs=Math.floor(differenceInMilliseconds),isNaN(days)||isNaN(hours)||isNaN(mins)?document.getElementById(e).innerHTML="No expiration information":(0!=days&&(out+=days+" <span class='expires-in-units'>d</span> "),0!=hours&&(out+=hours+" <span class='expires-in-units'>hr</span> "),out+=mins+" "+(1==mins?"<span class='expires-in-units'>min</span>":"<span class='expires-in-units'>min</span></span>")+" ",out=out.substr(0,out.length-2),document.getElementById(e).innerHTML=
out))}function isExpired(a){d=new Date;var b=new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours(),d.getUTCMinutes(),d.getUTCSeconds(),d.getUTCMilliseconds());timeNow=new Date;differenceInMilliseconds=a.getTime()-b.getTime();delete timeNow;return 0>differenceInMilliseconds?1:0}
function highlightSelectedMarker(){if(0!=markersArray.length){var a=markersArray[selectedMarkerIndex].categoryIDs[0];markersArray[selectedMarkerIndex].setIcon(new google.maps.MarkerImage("/images/markers.png",new google.maps.Size(31,37),new google.maps.Point(460+31*a,0),new google.maps.Point(16,37)))}}
function calculateCityEditionFromLatLng(a,b){a=parseFloat(a);b=parseFloat(b);if(isNaN(a)||isNaN(a))return 0;for(var c=1E6,e,f,g=0;g<cityLat.length;g++)0!=cityLat[g]&&(e=distance(a,b,cityLat[g],cityLng[g]),e<c&&(c=e,f=g));return f};
